apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: abus-matomo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: abus-matomo-dep
    spec:
      containers:
      - name: abus-matomo-web
        image: bcrdc.azurecr.cn/abusmatomo:test
        ports:
        - containerPort: 6379
          name: abusmatomo
---
apiVersion: v1
kind: Service
metadata:
  name: azure-matomo-svc
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: abus-matomo-dep
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: azure-vote-front
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: abus-entry
  annotations:
    kubernetes.io/ingress.class: "nginx2"
spec:
  tls:
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: azure-vote-front
          servicePort: 80
---

